### ISSUE TITLE
Doesn't work with trapd00r/LS_COLORS

### ISSUE THREAD

**Issue by Aloxaf** [xPMo/zsh-ls-colors#9]
When I ran simple-ls, I got the following result:

![image](https://user-images.githubusercontent.com/17017672/109021557-f38b7480-76f5-11eb-9652-0c2f6de0a108.png)

If I remove `bd=38;5;68:ca=38;5;17:cd=38;5;113;1:di=38;5;30:do=38;5;127:ex=38;5;208;1:pi=38;5;126:fi=0:ln=target:mh=38;5;222;1:no=0:or=48;5;196;38;5;232;1:ow=38;5;220;1:sg=48;5;3;38;5;0:su=38;5;220;1;3;100;1:so=38;5;197:st=38;5;86;48;5;234:tw=48;5;235;38;5;139;3` from the definition of LS_COLORS, then the result is:

![image](https://user-images.githubusercontent.com/17017672/109021773-29305d80-76f6-11eb-94a9-1e21c034fd33.png)

Seems that they are in conflict.

**Comment by xPMo** [comment]
The issue is `fi=0`. I need to tweak the logic so that for normal files, it checks namecolors *first*, then falls back to modecolors.

**Comment by xPMo** [comment]
Thanks for the report!
